version: "3"

services:
  frps:
    image: fatedier/frps
    container_name: frps
    ports:
      - "7000:7000"
      - "7777:7777"
      - "8888:8888
    volumes:
      - ./frps/frps.ini:/frps.ini
    command: -c /frps.ini
    environment:
      - FRP_TOKEN=${FRP_TOKEN}
    restart: always

  frpc:
    image: fatedier/frpc
    container_name: frpc
    network_mode: "host"
    volumes:
      - ./frpc/frpc.ini:/frpc.ini
    command: -c /frpc.ini
    environment:
      - FRP_TOKEN=${FRP_TOKEN}
    restart: always
