---
- name: Setup FRP Server with Docker
  hosts: frp_server
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common]
        state: present
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy docker-compose files
      copy:
        src: ../
        dest: /opt/frp/
        owner: root
        group: root
        mode: '0755'

    - name: Start FRPS container
      shell: docker-compose up -d frps
      args:
        chdir: /opt/frp/